apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nestjs-metrics
  name: nestjs-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-metrics
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nestjs-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "3000"        
    spec:
      containers:
      - image: anan/nestjs-metrics
        name: nestjs-metrics
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
status: {}
